"root_frame" : "map"
"robot_prefix" : "X1/"
"tf_buffer_size" : 10
"waypoint_reach_dist" : 2.
"waypoint_gap" : 0.1
"course" : "reactive" # trn/tst/obst/tradr/reactive
"rough_waypoint_list_trn" : [[1,0,0.1],
                             [2,0,0.2],
                             [3,0,0.1],
                             [4,0,0.2],
                             [5,0,0.2],
                             [6,0,0.4],
                             [7,0,0.4],
                             [8.5,0,0.1],
                             [8,1,0.2],
                             [8,2,0.1],
                             [8,3,0.1],
                             [7,3,0.2],
                             [6,3,0.2],
                             [5,3,0.1],
                             [4,3,0.2],
                             [3,3,0.2],
                             [2,3,0.3],
                             [1,3,0.2],
                             [0,3,0.1],
                             [-1,3,0.2],
                             [-2,3,0.4],
                             [-3,3,0.2],
                             [-4,3,0.1],
                             [-5,3,0.2],
                             [-6,3,0.1],
                             [-7,3,0.2],
                             [-8,3,0.2],
                             [-9,3,0.1],
                             [-9,2,0.2],
                             [-9,1,0.2],
                             [-9,0,0.1],
                             [-8,0,0.1],
                             [-7,0,0.3],
                             [-6,0,0.3],
                             [-5,0,0.3],
                             [-4,0,0.6],
                             [-3,0,0.8],
                             [-2,0,0.6],
                             [-1,0,0.3],
                             [0,0,0.1]]

"rough_waypoint_list_tst" : [[1,0,0.1],
                             [2,0,0.2],
                             [3,0,0.1],
                             [4,0,0.2],
                             [5,0,0.2],
                             [6,0,0.3],
                             [7,0,0.3],
                             [8,0,0.2],
                             [8,1,0.0],
                             [8,2,0.2],
                             [8,3,0.1],
                             [7,3,0.2],
                             [6,3,0.2],
                             [5,3,0.1],
                             [4,3,0.1],
                             [3,3,0.1],
                             [2,3,0.3],
                             [1,3,0.2],
                             [0,3,0.1],
                             [-1,3,0.2],
                             [-2,3,0.4],
                             [-3,3,0.2],
                             [-4,3,0.1],
                             [-5,3,0.1],
                             [-6,3,0.1],
                             [-7,3,0.3],
                             [-8,3,0.2],
                             [-9,3,0.1],
                             [-9,2,0.2],
                             [-9,1,0.2],
                             [-9,0,0.1],
                             [-8,0,0.2],
                             [-7,0,0.4],
                             [-6,0,0.5],
                             [-5,0,0.3],
                             [-4,0,0.3],
                             [-3,0,0.6],
                             [-2,0,0.4],
                             [-1,0,0.1],
                             [0,0,0.1]]

"rough_waypoint_list_obst" : [[1,0,0.1],
                              [3,0,0.1],
                              [5,0,0.1],
                              [8,0,0.1],
                              [8.0,1.5,0.1],
                              [0,1.5,0.1],
                              [0,0,0.1]]

"rough_waypoint_list_tradr" : [
                              [1,0,0.1],
                               [2,0,0.1],
                               [5,0,0.1],
                               [7,0,0.1],
                               [9,0,0.1],
                               [10,0,0.1],
                               [12,0,0.1],
                               [17,0,0.1],
                               [20,0,0.1]]

"rough_waypoint_list_reactive" : [
                              [1,0,0.1],
                               [2,0,0.1],
                               [5,0,0.1],
                               [7,0,0.1],
                               [9,0,0.1],
                    ]


