# Flippers
"enable_flippers" : True
"max_continuous_current" : 6
"max_peak_current" : 6
"peak_current_duration" : 3
"stuck_motor_min_speed" : 6
"mode" : "handcrafted" # handcrafted, learned
"ascending_thresh" : 0.07
"descending_thresh" : -0.07
"ascending_vel_factor" : 1
"stairs_vel_factor" : 1

# Flippers state - position dictionary
"FLIPPERS_NEUTRAL" : [-2, -2, 2, 2]
"FLIPPERS_ASCENDING_FRONT" : [-0.7, -0.7, 0.2, 0.2]
"FLIPPERS_ASCENDING_REAR" : [0, 0, -0.7, -0.7]
"FLIPPERS_DESCENDING_FRONT" : [0.5, 0.5, -0.3, -0.3]
"FLIPPERS_DESCENDING_REAR" : [0.5, 0.5, -0.9, -0.9]
"FLIPPERS_UP_STAIRS" : [0, 0, 0, 0]
"FLIPPERS_DOWN_STAIRS" : [0, 0, 0, 0]

# Flippers state - current dictionary
"FLIPPERS_CURRENT_NEUTRAL" : [1, 1]
"FLIPPERS_CURRENT_ASCENDING_FRONT" : [3, 1]
"FLIPPERS_CURRENT_ASCENDING_REAR" : [1, 5]
"FLIPPERS_CURRENT_DESCENDING_FRONT" : [0.5, 0.5]
"FLIPPERS_CURRENT_DESCENDING_REAR" : [0.5, 1]
"FLIPPERS_CURRENT_UP_STAIRS" : [1, 1]
"FLIPPERS_CURRENT_DOWN_STAIRS" : [1, 1]

# Tracker
"enable_cmd_vel" : True
"waypoint_reach_distance" : 0.7
"final_waypoint_reach_distance" : 0.4
"bidirectional_tracking" : True
"turn_vel_thresh" : 0.4 # Greater yaw deviations turn off linear velocity
"turn_inhibition_sensitivity" : 1 # Affects how turn error inhibits linear velocity
"turn_vel_sensitivity" : 2 # Sensitivity to linear error
"lin_vel_sensitivity" : 3 # Sensitivity to turn error
"strafe_vel_sensitivity" : 2 # Sensitivity to turn error
"cmd_vel_scalar" : 1. # Scales the final velocity outputs
"cmd_vel_lin_clip" : 1.5
"cmd_vel_strafe_clip" : 0.5
"cmd_vel_ang_clip" : 0.8
"initial_pc_cutoff_radius" : 3
"max_considered_path_lookahead_distance" : 2.0
"path_lookahead_pose_skip" : 5
"path_lookahead_trav_consideration_radius" : 0.4
"cmd_vel_lin_momentum" : 0.8
"cmd_vel_ang_momentum" : 0.6
"tracker_burn_in_time" : 1.5
"enable_lookahead" : False




