# Ros params
"node_name" : "spot_assistant"
"root_frame" : "map"
"spot_root_frame" : "body"
"planner_path_topic" : "rds/path"
"combined_path_topic" : "art/combined_path"
"traversability_visual_topic" : "rds/traversability_visual"
"path_semantic_pts_topic" : "art/path_semantic_pts"
"force_dir_topic" : "art/force_dir"
"force_dir_odom_topic" : "art/force_dir_odom"
"slopes_dirs_topic" : "art/slopes_dirs"
"spot_walking_mode_topic" : "art/spot_walking_mode"
"tf_buffer_size" : 10
"ros_rate" : 5
"max_pc_points" : 4000
"path_lookahead_pose_skip" : 2
"max_path_lookahead_dist" : 3
"k_neighbors" : 20
"kd_tree_max_rad" : 0.3
"min_slope_for_dir_enforcement" : 26
"min_slope_stairs" : 26
"max_slope_stairs" : 60
"dir_enforcement_dist_threshold" : 1.5
"crawl_enforcement_dist_threshold" : 1.5
"mean_trav_crawl_thresh" : 1.1
"enable_force_dir_setting" : True
"enable_stairs_mode_setting" : True
"enable_locom_setting" : True
"permanently_force_crawl_mode" : False

# Gait codes
"HINT_AUTO" : 1
"HINT_TROT" : 2
"HINT_CRAWL" : 4
"HINT_AMBLE" : 5
"HINT_SPEED_SELECT_AMBLE" : 6
"HINT_SPEED_SELECT_CRAWL" : 10
