"train" : True
"test" : True
"test_agent_ID" : "TRN"
"cma_std" : 0.3
"dsm_lr" : 0.015
"sc_lr" : 0.005
"dsm_iters" : 1500
"dsm_d_iters" : 5000
"dsm_batchsize" : 200
"state_classifier_iters" : 10000
"sc_batchsize" : 200
"bbx_iters" : 5000
"feat_vec_dim" : 9
"linear" : True
"weight_decay" : 0.001
"random_mask_prob" : 0.0 # 0.6 - does not correspond to dropout rate
<<<<<<< HEAD
"data_dir_name" : "sm_full"
"balance_dataset" : False 
#"mode" : "state_classification" # handcrafted_sm/bbx_sm/differentiable_sm/differentiable_detached_sm/state_classification/neutral/random/

=======
"data_dir_name" : "sm_reimp"
"balance_dataset" : False
"modes" : ["reimp"] # handcrafted_sm/bbx_sm/differentiable_sm/differentiable_detached_sm/state_classification/neutral/random/
>>>>>>> bf35b9f9db911efa610c8f3daa1c80d9a381fc08
